spring:
    jackson:
        mapper:
            ACCEPT_CASE_INSENSITIVE_ENUMS: true
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:mem:flow
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

